sudo: required

language: bash

branches:
 only:
 - master
 - production

services:
  - docker

before_install:
   - docker build -t e5pe/mads-todolist-2017:$TRAVIS_BUILD_NUMBER .

script:
   - docker run --rm e5pe/mads-todolist-2017:$TRAVIS_BUILD_NUMBER /bin/bash -c "sbt test"
   - docker run -d --rm -p 3306:3306 --name play-mysql -e MYSQL_ROOT_PASSWORD=mads -e MYSQL_DATABASE=mads mysql
   - docker run --link play-mysql:mysql --rm -e DB_URL="jdbc:mysql://play-mysql:3306/mads" -e DB_USER_NAME="root" -e DB_USER_PASSWD="mads" e5pe/mads-todolist-2017:$TRAVIS_BUILD_NUMBER /bin/bash -c "sbt '; set javaOptions += \"-Dconfig.file=conf/integration.conf\"; test'"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push e5pe/mads-todolist-2017:$TRAVIS_BUILD_NUMBER;
    docker tag e5pe/mads-todolist-2017:$TRAVIS_BUILD_NUMBER e5pe/mads-todolist-2017:latest;
    docker push e5pe/mads-todolist-2017:latest;
    fi
